#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-childprocess
Version  : 0.5.6
Release  : 4
URL      : https://rubygems.org/downloads/childprocess-0.5.6.gem
Source0  : https://rubygems.org/downloads/childprocess-0.5.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext
BuildRequires : rubygem-yard

%description
# childprocess
This gem aims at being a simple and reliable solution for controlling
external programs running in the background on any Ruby / OS combination.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n childprocess-0.5.6
gem spec %{SOURCE0} -l --ruby > rubygem-childprocess.gemspec

%build
gem build rubygem-childprocess.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
childprocess-0.5.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/childprocess-0.5.6
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/childprocess-0.5.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/_stdin%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/cdesc-AbstractIO.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/check_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/inherit%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/stderr%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/stdin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/stdout%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractIO/stdout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/alive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/assert_started-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/cdesc-AbstractProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/crashed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/cwd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/detach%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/detach-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/duplex%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/duplex-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/environment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/exit_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/exited%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/launch_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/leader%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/leader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/poll_for_exit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/started%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/AbstractProcess/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/InvalidEnvironmentVariable/cdesc-InvalidEnvironmentVariable.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/IO/cdesc-IO.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/IO/check_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/cdesc-Process.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/create_stdin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/exited%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/launch_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/redirect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/set_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/setup_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/stdin/cdesc-stdin.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/stop_pumps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Process/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Pump/cdesc-Pump.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Pump/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Pump/pump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Pump/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/Pump/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/cdesc-JRuby.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/posix_fileno_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/JRuby/windows_handle_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/LaunchError/cdesc-LaunchError.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/MissingPlatformError/cdesc-MissingPlatformError.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/MissingPlatformError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/SubclassResponsibility/cdesc-SubclassResponsibility.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/TimeoutError/cdesc-TimeoutError.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/fetch_constant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/fetch_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/generate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/Generator/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Tools/cdesc-Tools.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/ForkExecProcess/cdesc-ForkExecProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/ForkExecProcess/launch_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/ForkExecProcess/set_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/IO/cdesc-IO.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/IO/check_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/cdesc-Attrs.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/flags%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/flags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/free-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/pgroup%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/Attrs/to_ptr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FFI/Library/cdesc-Library.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FFI/cdesc-FFI.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/add_close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/add_dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/add_open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/cdesc-FileActions.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/free-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/FileActions/to_ptr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/cdesc-Lib.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/check-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Lib/environ-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Platform/cdesc-Platform.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Argv/cdesc-Argv.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Argv/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Argv/to_ptr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Envp/cdesc-Envp.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Envp/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/Envp/to_ptr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/cdesc-PosixSpawnProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/fileno_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/PosixSpawnProcess/launch_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/_pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/cdesc-Process.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/exited%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/send_kill-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/send_signal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/send_term-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/set_exit_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/Process/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Unix/cdesc-Unix.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/cdesc-Handle.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/exit_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/pointer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/send-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Handle/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/IO/cdesc-IO.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/IO/check_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/IO/has_fileno%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/IO/has_to_io%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/IoCounters/cdesc-IoCounters.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/JobObjectBasicLimitInformation/cdesc-JobObjectBasicLimitInformation.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/JobObjectExtendedLimitInformation/cdesc-JobObjectExtendedLimitInformation.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/alive%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/cdesc-Lib.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/check_error-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/dont_inherit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/duplicate_handle-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/each_child_of-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/get_handle_inheritance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/handle_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/io_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/kill-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/last_error_message-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/msvcrt_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/no_hang%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/set_handle_inheritance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/wait_for_pid-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/waitpid-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Lib/waitpid2-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/Job/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/Job/cdesc-Job.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/Job/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/Job/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/cdesc-Process.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/close_handle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/close_job_if_necessary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/exited%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/launch_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/Process/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/cdesc-ProcessBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/close_handles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/create_command_pointer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/create_cwd_pointer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/create_environment_pointer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/create_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/cwd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/detach-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/duplex-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/environment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/process_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/quote_if_necessary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/setup_flags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/setup_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/startup_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/std_stream_handle_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/stdin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessBuilder/stdout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/ProcessInfo/cdesc-ProcessInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/SecurityAttributes/cdesc-SecurityAttributes.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/SecurityAttributes/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/StartupInfo/cdesc-StartupInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/arch-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/cdesc-ChildProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/close_on_exec-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/jruby%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/linux%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/os-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/platform-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/platform_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/posix_spawn%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/posix_spawn%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/unix%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/warn_once-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/ChildProcess/windows%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/FFI/MemoryPointer/cdesc-MemoryPointer.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/FFI/MemoryPointer/from_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/FFI/cdesc-FFI.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/Java/JavaIo/FileDescriptor/cdesc-FileDescriptor.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/Java/JavaIo/cdesc-JavaIo.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/Java/SunNioCh/FileChannelImpl/cdesc-FileChannelImpl.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/Java/SunNioCh/cdesc-SunNioCh.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/Java/cdesc-Java.ri
/usr/lib64/ruby/gems/2.2.0/doc/childprocess-0.5.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/.document
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/childprocess.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/coverage/.last_run.json
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/coverage/.resultset.json
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/coverage/.resultset.json.lock
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/abstract_io.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/abstract_process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/jruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/jruby/io.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/jruby/process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/jruby/pump.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/tools/generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/fork_exec_process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/io.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/lib.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/platform/i386-linux.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/platform/i386-solaris.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/platform/x86_64-linux.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/platform/x86_64-macosx.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/posix_spawn_process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/unix/process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/handle.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/io.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/lib.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/process.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/process_builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/lib/childprocess/windows/structs.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/abstract_io_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/childprocess_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/io_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/jruby_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/pid_behavior.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/unix_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/childprocess-0.5.6/spec/windows_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/childprocess-0.5.6.gemspec
